version: '3'

services:
  teste-postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "br@s1l"
    ports:
      - "15432:5432"
    volumes:
      - /home/luisjesus/Dev/Docker-Compose/PostgreSQL:/var/lib/postgresql/data
      networks:
      - postgres-compose-network
      
  teste-pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "luisjesus.ti@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "br@s1l"
    ports:
      - "16543:80"
    depends_on:
      - teste-postgres-compose
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge